trigger:
- master
pr:
- master

parameters:
  - name: environment
    type: string
    default: devl
    values:
      - devl
      - prod

#variables:
#  - name: MAVEN_CACHE_FOLDER
#    value: $(Pipeline.Workspace)/.m2/repository
#  - name: isMain
#    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
#  - name: MAVEN_OPTS
#    value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
#  - name: imageName
#    value: 'myprojects-fp-api'
#  - name: imageTag
#    value: 'mypfpapi-$(Build.SourceVersion)'
#  - name: stackName
#    value: 'myprojects-fp-api-stack'
#  - name: devl-account
#    value: 278425112560
#  - name: prod-account
#    value: 334900618734
stages:
- stage: Build
  pool:
    name: devl-ipaas-agents
  jobs:
    - job: Build

      container:
        image: maven:3-jdk-8
      steps:
           - script: npm install -g npm@12.15.0
