trigger:
- master
pr:
- master

parameters:
  - name: environment
    type: string
    default: devl
    values:
      - devl
      - prod

#variables:
#  - name: MAVEN_CACHE_FOLDER
#    value: $(Pipeline.Workspace)/.m2/repository
#  - name: isMain
#    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
#  - name: MAVEN_OPTS
#    value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
#  - name: imageName
#    value: 'myprojects-fp-api'
#  - name: imageTag
#    value: 'mypfpapi-$(Build.SourceVersion)'
#  - name: stackName
#    value: 'myprojects-fp-api-stack'
#  - name: devl-account
#    value: 278425112560
#  - name: prod-account
#    value: 334900618734
stages:
- stage: PR_Verify
  pool:
    name: devops81-aws-supplymgmt-cost-forecasting-tracking-${{ parameters.environment }}-useast1-vpn-ec2-AMZ_Linux2_Java_DevTools
  jobs:
    - job: PR_Verify
      condition: eq(variables.isMain, false)
      container:
        image: maven:3-jdk-8
      steps:
        - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.11'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: false
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'package'
