--- 
parameters: 
  - 
    default: devl
    name: environment
    type: string
    values: 
      - devl
      - prod
pr: 
  - master
stages: 
  - 
    displayName: "PR Verify"
    jobs: 
      - 
        container: 
          image: "maven:3-jdk-8"
        job: PR_Verify
        steps: 
          - 
            inputs: 
              effectivePomSkip: false
              goals: install
              isJacocoCoverageReportXML: false
              javaHomeOption: JDKVersion
              mavenAuthenticateFeed: false
              mavenPomFile: pom.xml
              mavenVersionOption: Default
              sonarQubeRunAnalysis: false
              sqMavenPluginVersionChoice: pom
            task: Maven@3
          - 
            displayName: "Docker Build"
            inputs: 
              command: build
              containerRegistry: docker-deere
              repository: $(imageName)
              tags: "$(imageTag)\n"
            task: Docker@2
    pool: 
      name: devl-ipaas-agents
    stage: PR_Verify
trigger: 
  - master
variables: 
  - 
    name: imageName
  - "value:'customers-api'"
