trigger:
- master
pr:
- master

parameters:
  - name: environment
    type: string
    default: devl
    values:
      - devl
      - prod

#variables:
#  - name: MAVEN_CACHE_FOLDER
#    value: $(Pipeline.Workspace)/.m2/repository
#  - name: isMain
#    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
#  - name: MAVEN_OPTS
#    value: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
#  - name: imageName
#    value: 'myprojects-fp-api'
#  - name: imageTag
#    value: 'mypfpapi-$(Build.SourceVersion)'
#  - name: stackName
#    value: 'myprojects-fp-api-stack'
#  - name: devl-account
#    value: 278425112560
#  - name: prod-account
#    value: 334900618734
stages:
- stage: PR_Verify
  pool:
    name: devops81-aws-supplymgmt-cost-forecasting-tracking-${{ parameters.environment }}-useast1-vpn-ec2-AMZ_Linux2_Java_DevTools
  jobs:
    - job: PR_Verify
      condition: eq(variables.isMain, false)
      container:
        image: maven:3-jdk-8
      steps:
      - task: Cache@2
        inputs:
          key: 'maven | "$(Agent.OS)" | **/pom.xml'
          restoreKeys: |
            maven | "$(Agent.OS)"
            maven
          path: $(MAVEN_CACHE_FOLDER)
        displayName: Cache Maven local repo

      - task: DownloadSecureFile@1
        name: 'settings'
        inputs:
          secureFile: 'settings.xml'

      - task: Maven@3
        inputs:
          goals: 'install'
          mavenPomFile: pom.xml
          mavenOptions: '$(MAVEN_OPTS)'
          options: '-s $(settings.secureFilePath) -gs $(settings.secureFilePath) -B -e'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
          isJacocoCoverageReportXML: false
          sqMavenPluginVersionChoice: 'pom'
  displayName: 'PR Verify'

