trigger:
- master
pr:
- master

parameters:
  - name: environment
    type: string
    default: devl
    values:
      - devl
      - prod

stages:
- stage: PR_Verify
  pool:
    name: devl-ipaas-agents
  jobs:
    - job: PR_Verify
      
      container:
        image: maven:3-jdk-8
      steps:
      

      
      - task: Maven@3
        inputs:
          goals: 'install'
          mavenPomFile: pom.xml
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
          isJacocoCoverageReportXML: false
          sqMavenPluginVersionChoice: 'pom'

      - task: Docker@2
        displayName: 'Docker Build'
        inputs:
          repository: 'customers-api'
          containerRegistry: docker-deere
          command: build
          tags: |
            'customers-api-image'
            
  displayName: 'PR Verify'