openapi: 3.1.0
info:
  title: Customer.yml
  version: '1.0'
servers:
  - url: 'http://cusomter-api.deere.com'
paths:
  /customers:
    get:
      summary: ''
      operationId: get-customers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./CustomerInfo.yaml#/components/schemas/Customer
        '201':
          description: Created
      description: get all customers
  /customer:
    post:
      summary: ''
      operationId: post-customer
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
      description: Create new cusotmer
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./CustomerInfo.yaml#/components/schemas/Customer
          application/xml:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Customer'
        description: ''
components:
  schemas:
    Customer:
      title: Customer
      type: object
      properties:
        id:
          type: number
        firstName:
          type: string
        lastName:
          type: string
        title:
          type: string
        gender:
          type: string
        phone:
          type: string
        email:
          type: string
