echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "*****************HELLO VENKAT ! I AM GOING TO CLEAN THE PROJECT****************"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
mvn clean
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "******HELLO VENKAT ! PROJECT CLEANING  IS COMPLETED"
echo "******HELLO VENKAT ! I AM GOING TO PACKAGE THE PROJECT"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
mvn package -P local
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "********HELLO VENKAT ! PACKAGING  THE PROJECT COMPLETED"
echo "********HELLO VENKAT ! I AM GOING TO STOP THE CONTAINER"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
docker container stop customerapi_container
echo ""
echo ""
echo ""
echo ""
echo ""
echo "*********HELLO VENKAT ! STOPPING THE CONTAINER  COMPLETED"
echo "*********HELLO VENKAT ! I AM GOING TO REMOVE THE CONTAINER"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""

docker container rm customerapi_container

echo ""
echo ""
echo ""
echo "HELLO VENKAT ! REMOVING THE CONTAINER COMPLETED"
echo "HELLO VENKAT ! I AM GOING TO REMOVEE THE PROJECT"
echo ""
echo ""
echo ""


docker rmi customerapi_image
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "HELLO VENKAT ! IMAGE WAS REMOVED "
echo "HELLO VENKAT ! GOING TO CREATE IMAGE"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
docker build . -t customerapi_image


echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "HELLO VENKAT ! CREATION OF IMAGE COMPLETED"
echo "HELLO VENKAT ! I AM GOING TO RUN THE CONTAINER"
echo ""
echo ""
echo ""
echo ""
echo ""
docker run -p 8080:8080  --name=customerapi_container customerapi_image

