# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
           mvn -B package --file pom.xml
           mkdir artifacts && cp target/*.jar artifacts
           cd artifacts && ls
    - name: Save artifact 
      uses: actions/upload-artifact@v2
      with:
        name: github-actions-artifact
        path: artifacts
   
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.15.0'
        
    - name: Run the springboot
      run: |
           java -jar target/customers-api-0.0.1-SNAPSHOT.jar
    
    
        
        

   
