# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master1 ]
  pull_request:
    branches: [ master1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: |
           mvn -B package --file pom.xml
           mkdir artifacts && cp target/*.jar artifacts
           cd artifacts && ls
    - name: Save artifact 
      uses: actions/upload-artifact@v2
      with:
        name: github-actions-artifact
        path: artifacts
   
    - name: Run the springboot
      run: |
           java -jar target/customers-api-0.0.1-SNAPSHOT.jar &
           sleep 1
    - name: Contract Tests
      run: |
           curl --silent http://localhost:8080/healthz             

    - name: Setup Node 12.15.0
      uses: actions/setup-node@v3
      with:
        node-version: 12.15.0
#         cache: npm
   
    - name: Check and confirm node installation
      run: |
             npm -v  
  
    - name: Install Prism
      run: |
             npm install -g @stoplight/prism-cli  
  
    - name: Check and confirm prism installation
      run: |
             prism --version  
    - name: Start prism proxy server
      run: |
             prism proxy -p 4011 --errors Customer.yaml http://localhost:8080 &
             sleep 1
             
    - name: Verify specification
      run: |
             curl http://127.0.0.1:4011/customers
              $lineRate =curl -s -o /dev/null -w "%{http_code}" curl http://127.0.0.1:4011/customers
              Write-Output "::set-output name=lineRate::$lineRate"

             
             
